### ISSUE TITLE
Project bootstrap documentation

### ISSUE THREAD

**Issue by MateuszRostkowski** [binarapps/expo-ts-template#35]
Currently we have great bootstrap script, but it's not documented at all. We need to create some instructions for developers to help them creating projects faster.

**Comment by MSzalowski** [comment]
Will do that! 👍

**Comment by MateuszRostkowski** [comment]
@MSzalowski 

It's almost done, we should review it and check what's missing there

**Comment by MSzalowski** [comment]
Ah, yeah - so I won't 😅. To not interrupt the process, maybe lets assign people to the issues 🤔
